services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: incubadora
      POSTGRES_USER: incubadora
      POSTGRES_PASSWORD: incubadora
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - incubadora_net

  api:
    build:
      context: ..
      dockerfile: backend/Dockerfile
    restart: always
    env_file:
      - ../.env
    depends_on:
      - db
    networks:
      - incubadora_net

  web:
    build:
      context: ../frontend/pwa
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - api
    networks:
      - incubadora_net

  nginx:
    image: nginx:1.27-alpine
    depends_on:
      - web
      - api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ops/nginx/default-ssl.conf:/etc/nginx/conf.d/default.conf:ro
      - ./ops/nginx/certs:/etc/nginx/certs:ro


networks:
  incubadora_net:
    driver: bridge

volumes:
  db_data:
